schema_version: 1

context:
  version: "0.103.1"

package:
  name: python-substrait-protobuf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/substrait-protobuf/substrait_protobuf-${{ version }}.tar.gz
  sha256: a7688ce0705d3cee88ff99218c68188d7466837f7c6fbc6e6dfc8053427ac9e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - pip
  run:
    - python >=${{ python_min }}
    - protobuf >=5,<7

tests:
  - python:
      imports:
        - substrait.plan_pb2
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Generated Substrait Protocol Buffer Code
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://substrait.io
  repository: https://github.com/substrait-io/substrait-packaging

extra:
  mappings:
    python:
      pypi: substrait-protobuf
      import_name: substrait.plan_pb2
  recipe-maintainers:
    - westonpace
    - epsilonprime
    - jacques-n
    - yongchul
    - benbellick
    - vbarua
    - nielspardon
