schema_version: 1

context:
  version: "0.97.0"

package:
  name: python-substrait-protobuf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/substrait-protobuf/substrait_protobuf-${{ version }}.tar.gz
  sha256: d6be4ef0c2ad31b5ca2294e668d8dd02738940f680ffda1d4ae80e07b9614ef3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - pip
  run:
    - python >=${{ python_min }}
    - protobuf >=5,<7

tests:
  - python:
      imports:
        - substrait.plan_pb2
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Generated Substrait Protocol Buffer Code
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://substrait.io
  repository: https://github.com/substrait-io/substrait-packaging

extra:
  recipe-maintainers:
    - jacques-n
    - yongchul
    - benbellick
    - vbarua
    - nielspardon
