schema_version: 1

context:
  version: "0.96.0"

package:
  name: python-substrait-protobuf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/substrait-protobuf/substrait_protobuf-${{ version }}.tar.gz
  sha256: d8f3e29f6654e33e9b72d5f7570632389ce40085070e8990aeb500d573f3993f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - pip
  run:
    - python >=${{ python_min }}
    - protobuf >=5,<7

tests:
  - python:
      imports:
        - substrait.plan_pb2
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Generated Substrait Protocol Buffer Code
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://substrait.io
  repository: https://github.com/substrait-io/substrait-packaging

extra:
  recipe-maintainers:
    - yongchul
    - benbellick
    - vbarua
    - nielspardon
